use anyhow::Result;
use colored::Colorize;
use serde::Deserialize;

use crate::config;

/// Schema entry for a required variable (matches .envsafe.yaml format)
#[derive(Debug, Deserialize)]
struct VarSchema {
    name: String,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    pattern: Option<String>,
    #[serde(default)]
    r#type: Option<String>,
    #[serde(default)]
    default: Option<serde_yaml::Value>,
}

/// Top-level schema structure
#[derive(Debug, Deserialize)]
struct Schema {
    #[serde(default)]
    required: Vec<VarSchema>,
}

/// Try to find and parse .envsafe.yaml for variable descriptions
fn load_schema() -> Option<Schema> {
    let mut current = std::env::current_dir().ok()?;
    loop {
        let candidate = current.join(".envsafe.yaml");
        if candidate.exists() {
            let content = std::fs::read_to_string(&candidate).ok()?;
            return serde_yaml::from_str(&content).ok();
        }
        let candidate = current.join(".envsafe.yml");
        if candidate.exists() {
            let content = std::fs::read_to_string(&candidate).ok()?;
            return serde_yaml::from_str(&content).ok();
        }
        if !current.pop() {
            return None;
        }
    }
}

/// Generate a .env.example file from vault keys and schema descriptions
pub fn execute(env: &str) -> Result<()> {
    let project_config = config::find_project_root()?;
    let vault = crate::vault::Vault::load(&project_config)?;
    let vars = vault.get_env_vars(env)?;

    if vars.is_empty() {
        println!("No variables found in [{}]. Nothing to generate.", env);
        return Ok(());
    }

    // Load schema for descriptions (optional)
    let schema = load_schema();
    let schema_map: std::collections::HashMap<String, &VarSchema> = schema
        .as_ref()
        .map(|s| s.required.iter().map(|v| (v.name.clone(), v)).collect())
        .unwrap_or_default();

    let mut output = String::new();
    output.push_str("# Environment template generated by envsafe\n");
    output.push_str(&format!("# Source environment: {}\n", env));
    output.push_str("#\n");
    output.push_str("# Fill in the values below and rename to .env\n\n");

    for (key, _value) in &vars {
        // Add description comment if available from schema
        if let Some(var_schema) = schema_map.get(key) {
            if let Some(desc) = &var_schema.description {
                output.push_str(&format!("# {}\n", desc));
            }
            if let Some(pattern) = &var_schema.pattern {
                output.push_str(&format!("# Pattern: {}\n", pattern));
            }
            if let Some(type_name) = &var_schema.r#type {
                output.push_str(&format!("# Type: {}\n", type_name));
            }
            if let Some(default) = &var_schema.default {
                let default_str = match default {
                    serde_yaml::Value::String(s) => s.clone(),
                    other => format!("{:?}", other),
                };
                output.push_str(&format!("# Default: {}\n", default_str));
            }
        }
        output.push_str(&format!("{}=\n\n", key));
    }

    // Write to .env.example
    let output_path = project_config.project_root.join(".env.example");
    std::fs::write(&output_path, &output)?;

    println!(
        "{} Generated .env.example with {} variable(s) from [{}]",
        "done!".green().bold(),
        vars.len(),
        env
    );

    if schema.is_some() {
        println!(
            "  {} Included descriptions from .envsafe.yaml",
            "info:".cyan()
        );
    }

    Ok(())
}
